#ifndef TELEMETRY_UPLOAD_RESULT_H
#define TELEMETRY_UPLOAD_RESULT_H

enum TelemetryUploadStatus {
    TELEMETRY_UPLOAD_SUCCESS,
    TELEMETRY_UPLOAD_SENSOR_UNAVAILABLE,
    TELEMETRY_UPLOAD_PAYLOAD_INVALID,
    TELEMETRY_UPLOAD_NETWORK_ERROR,
    TELEMETRY_UPLOAD_HTTP_RETRYABLE,
    TELEMETRY_UPLOAD_HTTP_REJECTED,
    TELEMETRY_UPLOAD_DISABLED
};

struct TelemetryUploadResult {
    TelemetryUploadStatus status;
    int detailCode;
};

#endif